cache:
  paths:
    - node_modules/

stages:
  - build

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - echo "$CI_DOCKER_TOKEN" |  docker login -u $CI_DOCKER_USER --password-stdin
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master
