cache:
  paths:
    - node_modules/

stages:
  - build

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker login -u "$CI_DOCKER_USER" -p "$CI_DOCKER_TOKEN" $CI_REGISTRY
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master
